DnD/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dnd_app.urls')),
]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dnd_main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('', include('dnd.urls')),
]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lists/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo_list.urls')),
    path('', include('django.contrib.auth.urls'))

]

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls")),

    ]

models/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('model.urls'))
]

todo_list/urls.py
from django.urls import path, re_path, include
from django.views.decorators.cache import cache_page

from . import views
from .views import TaskListView, TaskCreateView, TaskDetailView, TaskUpdateView, TaskDeleteView, comprehension, \
    UserListView, UserDetailView, UserRedirectView, TaskArchiveIndexView, IceCreamListView, product_create_view, \
    feedback_view, create_post, SendingDetailView, product_list, document_list_view, register_view, UserViewSet, \
    TaskDetailViewSet, TaskListViewSet
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from rest_framework.routers import DefaultRouter
from .views import TaskViewSet
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

app_name = 'tasks'

router = DefaultRouter()
router.register(r'tasks', TaskViewSet)
router.register(r'users', UserViewSet)

urlpatterns = [
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/', include(router.urls)),
    re_path('^$', TaskListView.as_view(), name='task-list'),
    re_path('^create/$', TaskCreateView.as_view(), name='task-create'),
    path('<int:pk>/', TaskDetailView.as_view(), name='task-detail'),
    path('<int:pk>/update/', TaskUpdateView.as_view(), name='task-update'),
    path('<int:pk>/delete/', TaskDeleteView.as_view(), name='task-delete'),
    path('compr/', comprehension, name='comprehension'),
    # home_39
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='tasks:task-list'), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    path('register/', register_view, name='register'),

    path('users/', UserListView.as_view(), name='users'),
    path('user/<int:user_id>/', UserDetailView.as_view(), name='user_detail'),
    path('user/redirect/', UserRedirectView.as_view(), name='user_redirect'),
    path('tasks/archive/', TaskArchiveIndexView.as_view(), name='task_archive'),
    path('create_icecream/', views.create_icecream, name='create_icecream'),
    path('icecream_list/', IceCreamListView.as_view(), name='icecream_list'),
    #26
    path('create_product/', product_create_view, name='create_product'),
    #27
    path('create_multiple_tasks/', views.create_multiple_tasks, name='create_multiple_tasks'),
    #29
    path('playlist/', views.playlist_list, name='playlist_list'),
    path('playlists/<int:pk>/', views.playlist_detail, name='playlist_detail'),
    path('playlists/create/', views.playlist_create, name='playlist_create'),
    path('songs/create/', views.song_create, name='song_create'),
    path('create_product/', views.create_product_and_playlist_view, name='create_product_and_playlist'),
    path('products/', product_list, name='product_list'),
    # home_32
    path('feedback/', feedback_view, name='feedback'),
    # home_33
    path('profile/edit/', views.edit_profile, name='profile-edit'),
    # home_34
    path('create/post', create_post, name='create_post'),
    path('send/<int:pk>', SendingDetailView.as_view(), name='view_send'),
    # home_35
    path('accordion/', views.show_accordion, name='accordion'),
    path('alert/', views.show_alert, name='alert'),
    # home_38
    path('documents/', document_list_view, name='document-list'),
    path('upload/', views.upload_file_view, name='upload_file'),
    # home_43
    path('send-reset-emails/', views.send_reset_password_on_emails, name='send_reset_emails'),

    # home_44_for_test
    # path('tasks/', views.tasks_view, name='tasks_view'),

    # home_45
    path('users/', views.user_list, name='user_list'),
    path('users/<int:user_id>/', views.user_detail, name='user_detail'),

    # home_51_52
    path('tasks/api/<int:pk>', TaskDetailViewSet.as_view(), name='task_detail_api'),
    path('tasks/api/', TaskListViewSet.as_view(), name='task_list_api'),
]

templates/playlist/feedback.html
{%  extends "tasks/base.html" %}

{% block content %}
<form method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Отправить">
</form>
{% endblock %}

templates/playlist/playlist_detail.html
{%  extends "tasks/base.html" %}

{% load half_str %}



{% block content %}
<h2>{{playlist.name|half_str}}</h2>
<p>{{ playlist.description }}</p>

<h3>Songs:</h3>
<ul>
  {% for song in playlist.songs.all %}
  <li>{{song.artist}} - {{ song.title }}({{ song.duration }})</li>
  {% endfor %}
</ul>
{% endblock %}

templates/playlist/playlist_form.html
{% extends "tasks/base.html" %}

{% block content %}
<h2>Create New Playlist</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Create Playlist</button>
</form>

{% endblock %}

templates/playlist/playlist_list.html
{% extends "tasks/base.html" %}

{% block content %}
<h2>Playlists</h2>
<ul>
    {% for playlist in playlists %}
    <li>
        <a href="{% url 'tasks:playlist_detail' pk=playlist.pk %}">{{ playlist.name }}</a>

    </li>
    {% endfor %}
</ul>
{% endblock %}

templates/playlist/profile_edit.html
{% extends "tasks/base.html" %}

{% block title%} Добавить новую песню {% endblock %}

{% block content %}
  <h2>Зарегистрируйтесь для прослушивания плейлиста</h2>
  <form method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit">Зарегистрироваться</button>
  </form>
{% endblock %}

templates/playlist/song_form.html
{% extends "tasks/base.html" %}

{% block title%} Добавить новую песню {% endblock %}

{% block content %}
  <h2>Добавить новую песню</h2>
  <form method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit">Добавить песню</button>
  </form>
{% endblock %}