DnD/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dnd_app.urls')),
]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lists/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo_list.urls')),
    path('', include('django.contrib.auth.urls'))

]

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls")),

    ]

models/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('model.urls'))
]

testapp/urls.py
from django.urls import path

from testapp.views import AddSms, ReadSms, add, edit, index, get

app_name = 'testapp'

urlpatterns = [
    path('addsms/', AddSms.as_view(), name='add_sms'),
    path('readsms/<int:pk>/', ReadSms.as_view(), name='read_sms'),
    path('add/', add, name='add'),
    path('edit/<int:pk>/', edit, name='edit'),
    path('', index, name='index'),
    path('get/<path:filename>/', get, name='get'),
]

testapp/models.py
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.core.validators import FileExtensionValidator
from django.db import models
from django.contrib.auth.models import User

from bboard.models import Rubric, get_timestamp_path


class AdvUser(models.Model):
    is_activated = models.BooleanField(
        default=True,
    )

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE
    )


class Spare(models.Model):
    name = models.CharField(max_length=30)


class Machine(models.Model):
    name = models.CharField(max_length=30)
    spares = models.ManyToManyField(Spare, through='Kit',
                                    through_fields=('machine', 'spare'))
    notes = GenericRelation('Note')


class Kit(models.Model):
    machine = models.ForeignKey(Machine, on_delete=models.CASCADE)
    spare = models.ForeignKey(Spare, on_delete=models.CASCADE)
    count = models.IntegerField()


class SMS(models.Model):
    comment = models.CharField(max_length=120)

    sender = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="sender"
    )

    receiver = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="receiver"
    )


class Note(models.Model):
    content = models.TextField()
    content_type = models.ForeignKey(ContentType,
                                     on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey(ct_field='content_type',
                                       fk_field='object_id')

    class Meta:
        permissions = (
            ('hide_comments', 'Можно скрывать заметки'),
        )


# Прямое наследование
# ##
# class Message(models.Model):
#     content = models.TextField()


# class PrivateMessage(Message):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     message = models.OneToOneField(Message, on_delete=models.CASCADE,
#                                    parent_link=True)


# Абстрактные модели
# ##
class Message(models.Model):
    content = models.TextField()
    name = models.CharField(max_length=20)
    email = models.EmailField()

    class Meta:
        abstract = True
        ordering = ['name']


class PrivateMessage(Message):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)
    email = None

    class Meta(Message.Meta):
        pass


# Прокси-модели
class RevRubric(Rubric):
    class Meta:
        proxy = True
        ordering = ['-name']


class Img(models.Model):
    img = models.ImageField(
        verbose_name='Изображение',
        upload_to=get_timestamp_path,
        validators=[FileExtensionValidator(allowed_extensions=('jpg', 'png', 'gif'))]
    )

    desc = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = 'Изображение'
        verbose_name_plural = 'Изображения'

testapp/forms.py
from django import forms
from django.core import validators

from testapp.models import SMS, Img


class SMSCreateForm(forms.ModelForm):
    class Meta:
        model = SMS
        fields = ('sender', 'receiver', 'comment')


class ImgForm(forms.ModelForm):
    img = forms.ImageField(
        label='Изображение',
        validators=[validators.FileExtensionValidator(
            allowed_extensions=('gif', 'jpg', 'png'))],
        error_messages={
            'invalid_extension': 'Этот формат не поддерживается!'
        }
    )

    desc = forms.CharField(
        label='Описание',
        widget=forms.widgets.Textarea()
    )

    class Meta:
        model = Img
        fields = '__all__'

testapp/views.py
import os.path
from datetime import datetime

from django.db import transaction
from django.http import FileResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView,\
    DeleteView, UpdateView

from firstsite.settings import BASE_DIR
from testapp.forms import SMSCreateForm, ImgForm
from testapp.models import SMS, Img


FILES_ROOT = os.path.join(BASE_DIR, 'files')


class AddSms(CreateView):
    template_name = 'testapp/create.html'
    form_class = SMSCreateForm
    success_url = reverse_lazy('index')


class ReadSms(DetailView):
    model = SMS
    template_name = 'testapp/read.html'


def index(request):
    imgs = []

    for entry in os.scandir(FILES_ROOT):
        imgs.append(os.path.basename(entry))
        print('FILE: ', os.path.basename(entry))
    print(imgs)
    context = {'imgs': imgs}
    return render(request, 'testapp/index.html', context)


def get(request, filename):
    fn = os.path.join(FILES_ROOT, filename)
    return FileResponse(open(fn, 'rb'), content_type='application/octet-stream')


def add(request):
    if request.method == 'POST':
        form = ImgForm(request.POST, request.FILES)
        if form.is_valid():
            uploaded_file = request.FILES['img']
            fn = '%s%s' % (datetime.now().timestamp(),
                           os.path.splitext(uploaded_file.name)[1])
            fn = os.path.join(FILES_ROOT, fn)

            with open(fn, 'wb+') as destination:
                for chunk in uploaded_file.chunks():
                    destination.write(chunk)

            return redirect('testapp:index')
    else:
        form = ImgForm()

    context = {'form': form}

    return render(request, 'testapp/add.html', context)


def edit(request, pk):
    img = Img.objects.get(pk=pk)
    if request.method == 'POST':
        form = ImgForm(request.POST, request.FILES, instance=img)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = ImgForm(instance=img)

    context = {'form': form, 'img': img}

    return render(request, 'testapp/edit.html', context)

templates/testapp/add.html
{% extends "layout/basic.html" %}

{% block title %}Добавление изображеня{% endblock %}

{% block content %}
    <h2>Добавление изображеня</h2>

    <form method="post" enctype="multipart/form-data" class="col-md-4">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Отправить">
    </form>
{% endblock %}

templates/testapp/create.html
{% extends "layout/basic.html" %}

{% block title %}Отправка SMS{% endblock %}

{% block content %}
    <h2>Отправка SMS</h2>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Отправить">
    </form>
{% endblock %}

templates/testapp/delete.html
{% extends "layout/basic.html"%}

{% block content %}

<h1>Удалить SMS</h1>
<p>Вы уверены, что хотите удалить SMS "{{sms.comment}}"?</p>
<form method="post">
    {%csrf_token%}
    <input type="submit" value="Подтвердить" >
</form>
{%endblock%}

templates/testapp/edit.html
{% extends "layout/basic.html" %}

{% block title %}Изменение изображения{% endblock %}

{% block content %}
    <h2>Изменение изображения</h2>

    <div>
        <img src="{{ img.img.url }}" alt="Картинка">
    </div>

    <form method="post" enctype="multipart/form-data" class="col-md-4">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Отправить">
    </form>
{% endblock %}

templates/testapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<ul>
    {% for usr in all_users %}
    <div class="card" style="border-bottom:1px solid black; margin-bottom:35px">
        <li>{{ usr.username }}</li>
        <p>{{ usr.email }}</p>
        <p>{{ usr.first_name }}</p>
    </div>
    {% endfor %}
</ul>


{% for group in users_group %}
    <h2>Группы текущего пользователя</h2>
    {{ group.name }}
{% endfor %}

{% for img in imgs %}
<div class="image">
    <p>
        <img src="{% url 'testapp:get' filename=img %}" alt="">
    </p>
</div>
{% endfor %}

</body>
</html>

templates/testapp/list.html
{% extends "layout/basic.html" %}

{% block content %}
<h2>Sms List</h2>
<ul>
    {% for sms in sms_list %}
                <li>{{ sms.comment }}</li>
        {% empty %}
            <li>No messages</li>
        {% endfor %}
    </ul>
{% endblock %}
</ul>

templates/testapp/read.html
{% extends "layout/basic.html" %}

{% block content %}
    <h2>Сообщение:</h2>
    <p>От: {{ sms.sender }}</p>
    <p>Для: {{ sms.receiver }}</p>
    <p>{{ sms.comment }}</p>
{% endblock %}

templates/testapp/update.html
{% extends "layout/basic.html"%}

{% block content%}

<h2>Редактировать сообщение</h2>
<form method="post">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="Подтвердить">
</form>

{% endblock %}